In [33]:
import numpy as np

a = np.array([1, 2, 3, 4])

In [34]:
print("Dimesions:", a.ndim)
print("Shape:", a .shape)
print("Size:", a.size)

Dimesions: 1
Shape: (4,)
Size: 4


In [35]:
A = np.array([[1,2,3], [4, 5, 6]])

print("Dimesions:", A.ndim)  #2
print("Shape:", A.shape)
print("Size:", A.size)

Dimesions: 2
Shape: (2, 3)
Size: 6


In [36]:
A = np.array([1,2,3,4,5,6,7,8,9,0])
print("Shape of A:", A.shape) # 10,

B = A.reshape(2,5)
print(A)
print(B)
print("Shape of B:", B.shape)

Shape of A: (10,)
[1 2 3 4 5 6 7 8 9 0]
[[1 2 3 4 5]
 [6 7 8 9 0]]
Shape of B: (2, 5)


In [37]:
a

array([1, 2, 3, 4])

In [38]:
a[0]  #1

np.int64(1)

In [39]:
a[1:3]  # 2, 3

array([2, 3])

In [40]:
B

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [41]:
B[1,4] #0

np.int64(0)

In [42]:
B

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [43]:
B[0,2]

np.int64(3)

In [44]:
B[1,1]

np.int64(7)

In [45]:
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(4,3)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
#[[5,6], [8,9]]
c[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [47]:
#[[7,8], [10,11]]
c[2:,:2]

array([[ 7,  8],
       [10, 11]])

In [48]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
d = c[:,1]

In [50]:
d

array([ 2,  5,  8, 11])

In [51]:
d.shape  # 4,   1D array

(4,)

In [57]:
d = d.reshape(4,1) # 2d array
d.shape
print(d, d.shape, d.ndim)

[[ 2]
 [ 5]
 [ 8]
 [11]] (4, 1) 2


In [58]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
# [[3,6,9,12]]

e = c[:,2].reshape(4,1)
print(e, e.shape, e.ndim, e.size)  

[[ 3]
 [ 6]
 [ 9]
 [12]] (4, 1) 2 4


In [2]:
# identity matrix of 3

import numpy as np
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
B = np.zeros([2,3])
B

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.eye(5, k =-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [11]:
A = np.zeros([5,5])
A[1:,:-1] = np.eye(4)
A

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [12]:
np.eye(5, k =-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [13]:
np.eye(5, k = 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [14]:
B= np.zeros([5,5])
B[:-1, 1:] = np.eye(4)
B

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [58]:
C = np.zeros([5,5])
C[1:,:-1] = np.eye(4)
C2 = np.zeros([5,5])
C2[:-1,1:] = np.eye(4)
D = C+C2
D

array([[0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [18]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [20]:
B2 = np.array([[2,2], [2,2]])
B3 = np.array([[3,3,3],[3,3,3],[3,3,3]])

np.block([[B2, np.zeros([2,3])],[np.zeros([3,2]), B3]])

array([[2., 2., 0., 0., 0.],
       [2., 2., 0., 0., 0.],
       [0., 0., 3., 3., 3.],
       [0., 0., 3., 3., 3.],
       [0., 0., 3., 3., 3.]])

In [22]:
A = np.random.rand(3,4)
A

array([[0.8206747 , 0.50866179, 0.46407226, 0.68785509],
       [0.30327754, 0.16036334, 0.17670248, 0.49490899],
       [0.15872501, 0.62679743, 0.88140833, 0.98873461]])

In [28]:
np.diag([1,2,3]).shape # 3X3

(3, 3)

In [29]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.eye(3).shape # 3,3

(3, 3)

In [32]:
np.random.rand(2,3).shape

(2, 3)

In [34]:
np.random.randint(-10,10, size = (3,3))

array([[-5, -8,  7],
       [-5,  7, -9],
       [-3,  6,  5]], dtype=int32)

In [36]:
np.random.rand(5,5)

array([[0.15691145, 0.34546115, 0.22456012, 0.40056578, 0.16392715],
       [0.75378392, 0.92058256, 0.39644022, 0.71619571, 0.94498337],
       [0.99760082, 0.48740625, 0.62016106, 0.05698653, 0.60986781],
       [0.90459092, 0.20941669, 0.10825103, 0.51687969, 0.65818857],
       [0.12036171, 0.56399595, 0.09382047, 0.71299694, 0.30917507]])

In [37]:
np.random.randint(0,100, size=(5,5))

array([[16, 93, 18, 96, 97],
       [60, 84, 54, 64, 93],
       [70, 20, 19, 19, 66],
       [91, 84, 36, 84, 31],
       [41, 75, 78, 67, 40]], dtype=int32)

In [ ]:
v = np.array([2,3,4])
u = np.array([5,6,7])

x = np.dot(v, u) # 10+18+28
x

np.int64(56)

In [40]:
np.sqrt(np.dot(u,v)) #7.5...

np.float64(7.483314773547883)

In [43]:
45*45

2025

In [67]:
def norm(x):
    return np.sqrt(np.dot(x,x))

In [68]:
norm(u)

np.float64(10.488088481701515)

In [69]:
norm(v)

np.float64(5.385164807134504)

In [71]:
np.dot(C,C)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.array([[1,2], [1,2]])
b = np.array([[1,2], [1,2]])
c =np.dot(a,b)
np.sqrt(c)


array([[1.73205081, 2.44948974],
       [1.73205081, 2.44948974]])

In [77]:
def norm_M(x, y):
    return np.sqrt(np.dot(x,y))

In [78]:
norm_M(a,b)

array([[1.73205081, 2.44948974],
       [1.73205081, 2.44948974]])

In [62]:
C = np.eye(5)

In [64]:
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
norm_M(C, D)

array([[0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [80]:
import scipy.linalg as la

In [81]:
v

array([2, 3, 4])

In [ ]:
la.norm(v) # ~5....

np.float64(5.385164807134504)

In [86]:
a = np.array([1,0])
b = np.array([1,1])

cos_theta = np.dot(a,b)/ (norm(a)*norm(b))

In [88]:
cos_theta

np.float64(0.7071067811865475)

In [95]:
theta = np.arccos(cos_theta)
theta

np.float64(0.7853981633974484)

In [94]:
np.cos(np.pi/4)

np.float64(0.7071067811865476)

In [93]:
1/np.sqrt(2)

np.float64(0.7071067811865475)

In [98]:
def theta(x,y):
    return np.arccos((np.dot(x,y))/(la.norm(x)*la.norm(y)))

In [99]:
theta(a,b)

np.float64(0.7853981633974484)

In [101]:
c = np.array([-1,0])
theta(b,c)

np.float64(2.356194490192345)

In [103]:
A = np.array([1,2,3,4]).reshape(2,2)
B = np.array([2,5,7,1]).reshape(2,2)
A + B

array([[ 3,  7],
       [10,  5]])

In [104]:
c = np.dot(A,B)
c

array([[16,  7],
       [34, 19]])

In [105]:
d = A@B
d

array([[16,  7],
       [34, 19]])

In [110]:
e = np.array([1,2,3,4]).reshape(2,2)
f = np.array([1,2])

print(e)
print(f)

[[1 2]
 [3 4]]
[1 2]


In [111]:
np.dot(e,f)

array([ 5, 11])

In [112]:
e@f

array([ 5, 11])

In [114]:
np.dot(f,e)

array([ 7, 10])

In [115]:
f@e

array([ 7, 10])

In [116]:
A =np.array([1,2,2,1]).reshape(2,2)
B = np.array([1,1,1,1]).reshape(2,2)
I = np.eye(2)

eqn = 3*I + 2*A - (A@B)
eqn2 = 3*I + 2*A - (np.dot(A,B))
print(eqn)
print(eqn2)

[[2. 1.]
 [1. 2.]]
[[2. 1.]
 [1. 2.]]


In [117]:
A = np.array([1,2,-1,1]).reshape(2,2)
np.linalg.matrix_power(A,2)

array([[-1,  4],
       [-2, -1]])

In [120]:
A

array([[ 1,  2],
       [-1,  1]])

In [119]:
A**2

array([[1, 4],
       [1, 1]])

In [121]:
A

array([[ 1,  2],
       [-1,  1]])

In [122]:
A.T

array([[ 1, -1],
       [ 2,  1]])

In [124]:
np.transpose(A)

array([[ 1, -1],
       [ 2,  1]])

In [125]:
A

array([[ 1,  2],
       [-1,  1]])

In [126]:
np.linalg.inv(A)

array([[ 0.33333333, -0.66666667],
       [ 0.33333333,  0.33333333]])

In [127]:
B = np.array([1,2,3,4]).reshape(2,2)
np.linalg.inv(B)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [128]:
B.T

array([[1, 3],
       [2, 4]])

In [129]:
la.inv(B)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [130]:
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [131]:
np.trace(C)

np.float64(5.0)

In [133]:
C.trace()

np.float64(5.0)

In [136]:
B.transpose()

array([[1, 3],
       [2, 4]])

In [137]:
B

array([[1, 2],
       [3, 4]])

In [138]:
np.linalg.det(B)

np.float64(-2.0000000000000004)

In [139]:
import scipy.linalg as la
la.det(B)

np.float64(-2.0)

In [140]:
C = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [141]:
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
la.det(C)  # 1(45-48) -2(36-42) + 3(32-35) = -3+12-9 =0

np.float64(0.0)

In [144]:
np.linalg.det(C)

np.float64(0.0)

In [145]:
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
np.linalg.matrix_rank(C)

np.int64(2)

In [170]:
# check cayley-hamilton

def check_cayley_hamilton(x, n): # A is square matrix, n is the shape of square
    tr = np.trace(x)
    det = la.det(x)
    I = np.eye(n)
    
    return x@x - tr*x + det*I

In [171]:
B = np.array([7,7,7,8]).reshape(2,2)

In [172]:
check_cayley_hamilton(B,2)

array([[0., 0.],
       [0., 0.]])

In [174]:
def proj(v,w):
    return ((np.dot(v,w))/(np.dot(w,w))*w)

def perp(v,w):
    return v- proj(v,w)

In [176]:
v = np.array([4,2])
w = np.array([1,1])

projection = proj(v,w)
perpendicular = perp(v,w)

print(f"Projection of vecotr v on vector w: {projection}")
print(f"Perpedicular of vector v on vector w: {perpendicular}")

Projection of vecotr v on vector w: [3. 3.]
Perpedicular of vector v on vector w: [ 1. -1.]


In [186]:
x = np.array([1,3, -1])
y = np.array([1,1,2])

proj(x,y)

array([0.33333333, 0.33333333, 0.66666667])

In [187]:
perp(x,y)

array([ 0.66666667,  2.66666667, -1.66666667])

In [190]:
a = proj(x, y) + perp(x,y)
a

array([ 1.,  3., -1.])